name: TeamPlugin
version: 1.0
api-version: 1.20
main: me.vgauther.teamplugin.TeamPlugin
commands:
  createTeam:
    description: Crée une nouvelle équipe
    usage: /createTeam <teamName>
  joinTeam:
    description: Rejoint une équipe existante
    usage: /joinTeam <teamName>
  spawnQuestNPC:
    description: Fait apparaître un PNJ pour gérer les quêtes
    usage: /spawnQuestNPC
  checkTeam:
    description: Affiche l'équipe à laquelle vous appartenez
    usage: /checkTeam
  kickMember:
    description: Permet au chef d'équipe d'exclure un membre de l'équipe
    usage: /kickMember <playerName>
  acceptJoinRequest:
    description: Permet à un membre d'équipe d'accepter une demande de rejoindre l'équipe
    usage: /acceptJoinRequest <playerName> <teamName>